# Generated by Django 5.1.7 on 2025-05-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GENUIN_CODE', '0002_contact_customuser_lead_loginattempt_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Ragister',
        ),
    ]
